export const APP_ROUTES = {
  landing: "/",
  login: "/login",
  register: "/register",
  home: "/home",
  explore: "/explore",
  reels: "/reels",
  watch: "/watch",
  watchDetail: (slug: string) => `/watch/${slug}`,
  stories: "/stories",
  search: "/search",
  notifications: "/notifications",
  messages: "/messages",
  conversation: (id: string) => `/messages/${id}`,
  profile: "/profile",
  userProfile: (username: string) => `/u/${username}`,
  settings: "/settings",
  saved: "/saved",
  hashtag: (name: string) => `/hashtag/${name}`,
  analytics: "/analytics",
  createPost: "/create",
  postDetail: (slug: string) => `/p/${slug}`,
} as const;